-- migrate:up
CREATE TABLE user (
  id INT NOT NULL AUTO_INCREMENT,
  name TEXT  NOT NULL,
  email INT NOT NULL,
  type INT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
);
-- migrate:down
DROP TABLE user